version: '3.8'

services:
    mariadb:
        image: mariadb
        container_name: mariadb
        build: ./srcs/mariadb
        restart: always
        env_file:
            - .env
        volumes:
            - MariaDB:/var/lib/mysql
        networks: 
            - network
        
    wordpress:    
        image: wordpress
        container_name: wordpress
        build: ./srcs/wordpress
        restart: always
        env_file:
            - .env
        volumes:      
            - WordPress:/var/www/html
        networks: 
            - network
        depends_on:
            - mariadb

    nginx:
        image: nginx
        container_name: nginx
        build: ./srcs/nginx
        restart: always
        volumes:
            - WordPress:/var/www/html
        ports:      
            - "443:443"
        networks: 
            - network
        depends_on:
            -wordpress

volumes:
  MariaDB:
    name: MariaDB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chduong/data/mariadb

  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chduong/data/wordpress

networks:
    network:
        driver: bridge