version: '3.8'

services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - 
      - 
    ports:
      - "3306"
    networks:
      - net_inception
    restart: always
    env_file: .env

  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on :
      - wordpress
    ports:
      - 443:443
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks: 
      - network

  wordpress: