version: '3.8'

services:
    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        image: mariadb
        volumes:
            - MariaDB:/var/lib/mysql
        networks: 
            - backend
        restart: always
        env_file:
            - .env
        
    wordpress:    
        container_name: wordpress
        build: requirements/wordpress
        # image : wordpress:php7.3-fpm-alpine
        volumes:      
            - WordPress:/var/www/html
        ports:
            - '9000'
        depends_on:
            - mariadb    
        networks: 
            - backend
        restart: always  
        env_file:
            - .env

    nginx:
        container_name: nginx
        build: requirements/nginx
        image: nginx
        volumes:
            - WordPress:/var/www/html
        ports:      
            - "443:443"
        networks: 
            - backend
        restart: always

volumes:
  MariaDB:
    name: MariaDB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chduong/data/mariadb

  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chduong/data/wordpress

networks:
    backend:
        driver: bridge