version: '3'

services:
  mariadb:
    container_name: mariadb
    # build: requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql/
    ports:
      - "3306"
    networks:
      - default
    restart: unless-stopped
    env_file: .env

  nginx:
    container_name: nginx
    # build: requirements/nginx
    image: nginx:alpine
    depends_on :
      - wordpress
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - nginx:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    networks: 
      - default

  wordpress:
    container_name: wordpress
    # build: requirements/wordpress
    image : wordpress:php7.3-fpm-alpine
    depends_on:
      - mariadb
    restart: unless-stopped
    env_file:
      - .env
    ports:
     - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks: 
      - default

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/chduong/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/chduong/data/wordpress
      o: bind

networks:
  default:
    driver: bridge