version: '3.8'

services:
    mariadb:
        image: inception_mariadb
        container_name: mariadb
        build:
            context: ./srcs/mariadb
            args:
                - MYSQL_DATABASE={MYSQL_DATABASE}
                - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
                - MYSQL_USER={MYSQL_USER}
                - MYSQL_PASSWORD={MYSQL_PASSWORD}
        volumes:
            - MariaDB:/var/lib/mysql
        networks: 
            - network
        ports:
            - "3306:3306"
        restart: always
        env_file:
            - .env
        
    wordpress:    
        image: inception_wordpress
        container_name: wordpress
        build: ./srcs/wordpress
        volumes:      
            - WordPress:/var/www/html
        ports:
            - "9000:9000"
        depends_on:
            - mariadb    
        networks: 
            - network
        restart: always
        working_dir: /var/www/html
        env_file:
            - .env

    nginx:
        image: inception_nginx
        container_name: nginx
        build: ./srcs/nginx
        volumes:
            - WordPress:/var/www/html
        ports:      
            - "443:443"
        networks: 
            - network
        restart: always

volumes:
  MariaDB:
    name: MariaDB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chduong/data/mariadb

  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chduong/data/wordpress

networks:
    network:
        driver: bridge