version: '3.8'

services:
    mariadb:
        image: inception_mariadb
        container_name: mariadb
        build: ./srcs/mariadb
        restart: always
        volumes:
            - MariaDB:/var/lib/mysql
        networks: 
            - network
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            WP_DB_NAME: ${WP_DB_NAME}
            WP_DB_USER: ${WP_DB_USER}
            WP_DB_PASSWORD: ${WP_DB_PASSWORD}
        
    wordpress:    
        image: inception_wordpress
        container_name: wordpress
        build: ./srcs/wordpress
        restart: always
        volumes:      
            - WordPress:/var/www/html
        networks: 
            - network
        environment:
            DOMAIN_NAME: ${DOMAIN_NAME}
            MYSQL_HOST: ${MYSQL_HOST}
            WP_DB_NAME: ${WP_DB_NAME}
            WP_DB_USER: ${WP_DB_USER}
            WP_DB_PASSWORD: ${WP_DB_PASSWORD}
            WP_TITLE: ${WP_TITLE}
            WP_ADMIN_USER: ${WP_ADMIN_USER}
            WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
            WP_USER: ${WP_USER}
            WP_PASSWORD: ${WP_PASSWORD}
            WP_EMAIL: ${WP_EMAIL}
            WP_FILE_ONINSTALL: ${WP_FILE_ONINSTALL}

    nginx:
        image: inception_nginx
        container_name: nginx
        build: ./srcs/nginx
        volumes:
            - WordPress:/var/www/html
        ports:      
            - "443:443"
        networks: 
            - network
        restart: always

volumes:
  MariaDB:
    name: MariaDB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chduong/data/mariadb

  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/chduong/data/wordpress

networks:
    network:
        driver: bridge