version: '3'

services:
    mariadb:
        container_name: mariadb
        build: mariadb
        volumes:
            - MariaDB:/var/lib/mysql
        networks: 
            - backend 
        restart: always
        env_file:
            - .env
        
    wordpress:    
        container_name: wordpress
        # build: wordpress
        image : wordpress:php7.3-fpm-alpine
        volumes:      
            - WordPress:/var/www/html
        depends_on:
            - mariadb    
        networks: 
            - backend
        restart: always  
        env_file:
            - .env

    nginx:
        container_name: nginx
        build: nginx
        volumes:
            - WordPress:/var/www/html
        ports:      
            - "443:443"
        networks: 
            - backend
        restart: always

volumes:
  MariaDB:
    driver: local
    driver_opts:
      type: none
      device: /home/chduong/data/mariadb
      o: bind

  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /home/chduong/data/wordpress
      o: bind

networks:
    backend:
        driver: bridge