CREATE USER IF NOT EXISTS root@localhost IDENTIFIED BY 'rootpassword';
SET PASSWORD FOR root@localhost = PASSWORD('rootpassword');
GRANT ALL ON *.* TO root@localhost WITH GRANT OPTION;
CREATE USER IF NOT EXISTS root@'%' IDENTIFIED BY 'rootpassword';
SET PASSWORD FOR root@'%' = PASSWORD('rootpassword');
GRANT ALL ON *.* TO root@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS myuser@'%' IDENTIFIED BY 'userpassword';
SET PASSWORD FOR myuser@'%' = PASSWORD('userpassword');
CREATE DATABASE IF NOT EXISTS mydatabasename;
GRANT ALL ON mydatabasename.* TO myuser@'%';