version: '3'

services:
    mariadb:
        image: mariadb:alpine
        volumes:
            - MariaDB:/var/lib/mysql
        ports:   
            - 3306:3306
        environment:      
            MYSQL_ROOT_PASSWORD: mysql_root_pass      
            MYSQL_DATABASE: db_name      
            MYSQL_USER: user_name      
            MYSQL_PASSWORD: user_pass
        networks: 
            - default 
        restart: always
        
    wordpress:    
        image: wordpress:php7.3-fpm-alpine    
        volumes:      
            - WordPress:/var/www/html
        ports:   
            - 9000:9000
        depends_on:      
            - mariadb    
        environment:      
            WORDPRESS_DB_HOST: mysql      
            MYSQL_ROOT_PASSWORD: mysql_root_pass      
            WORDPRESS_DB_NAME: db_name      
            WORDPRESS_DB_USER: user_name      
            WORDPRESS_DB_PASSWORD: user_pass
        networks: 
            - default
        restart: always  
        
    nginx:
        container_name: nginx
        build: nginx
        depends_on:      
            - wordpress
        volumes:
            - WordPress:/var/www/html
        ports:      
            - 443:443
        networks: 
            - default
        restart: always

volumes:
  MariaDB:
    driver: local
    driver_opts:
      type: none
      device: /home/chduong/data/mariadb
      o: bind

  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /home/chduong/data/wordpress
      o: bind

networks:
  default:
    driver: bridge